server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8888
    connection-timeout: 5000
spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    datasource:
        platform: h2
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.h2.Driver
        druid:
            url: jdbc:h2:mem:template2;USER=sa;PASSWORD=456;DB_CLOSE_ON_EXIT=FALSE
            username: sa
            password: 456
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 'x'
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                login-username: admin
                login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                wall:
                    config:
                        multi-statement-allow: true
    h2:
        console:
            enabled: true
