version: '2'
services:
    template_maven-app:
        image: spring-boot-template
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://template_maven-mysql:3306/template_maven?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    template_maven-mysql:
        extends:
            file: mysql.yml
            service: template_maven-mysql
